---
name: Log-Handler
version: 0.38_09
author:
  - Jonny Schulz
abstract: Log messages to one or more outputs.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Devel::Backtrace: 0.05
  Fcntl: 0
  File::Spec: 0
  POSIX: 0
  Params::Validate: 0
  Sys::Hostname: 0
  Test::More: 0
  Time::HiRes: 0
  UNIVERSAL::require: 0
recommends:
  Config::General: 0
  Config::Properties: 0
  DBI: 0
  Net::SMTP: 0
  YAML: 0
provides:
  Log::Handler:
    file: lib/Log/Handler.pm
    version: 0.38_09
  Log::Handler::Config:
    file: lib/Log/Handler/Config.pm
    version: 0.00_05
  Log::Handler::Output:
    file: lib/Log/Handler/Output.pm
    version: 0.00_06
  Log::Handler::Output::DBI:
    file: lib/Log/Handler/Output/DBI.pm
    version: 0.00_02
  Log::Handler::Output::Email:
    file: lib/Log/Handler/Output/Email.pm
    version: 0.00_03
  Log::Handler::Output::File:
    file: lib/Log/Handler/Output/File.pm
    version: 0.00_03
  Log::Handler::Output::Forward:
    file: lib/Log/Handler/Output/Forward.pm
    version: 0.00_03
  Log::Handler::Plugin::Config::General:
    file: lib/Log/Handler/Plugin/Config/General.pm
    version: 0.00_03
  Log::Handler::Plugin::Config::Properties:
    file: lib/Log/Handler/Plugin/Config/Properties.pm
    version: 0.00_04
  Log::Handler::Plugin::Config::YAML:
    file: lib/Log/Handler/Plugin/YAML.pm
    version: 0.00_04
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
