---
name: Log-Handler
version: 0.38_03
author:
  - Jonny Schulz
abstract: A simple handler to log messages to log files.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Config::General: 0
  Devel::Backtrace: 0.05
  File::Spec: 0
  Params::Validate: 0
  Sys::Hostname: 0
  Test::More: 0
recommends:
  Config::Properties: 0
  YAML: 0
provides:
  Log::Handler:
    file: lib/Log/Handler.pm
    version: 0.38_03
  Log::Handler::Config:
    file: lib/Log/Handler/Config.pm
    version: 0.00_01
  Log::Handler::Logger:
    file: lib/Log/Handler/Logger.pm
    version: 0.00_03
  Log::Handler::Plugin::Config::General:
    file: lib/Log/Handler/Plugin/Config/General.pm
    version: 0.00_01
  Log::Handler::Plugin::Config::Properties:
    file: lib/Log/Handler/Plugin/Config/Properties.pm
    version: 0.00_01
  Log::Handler::Plugin::YAML:
    file: lib/Log/Handler/Plugin/YAML.pm
    version: 0.00_01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
